# CONFIGURAÇÃO (CLONAR PROJETO, CONFIGURAR AMBIENTE)

In [1]:
# ------------------------------------------------------------
# 1. Clonar o projeto GitHub -> Colab
# chave github: GITHUB_OBRAS_TOKEN
# ------------------------------------------------------------

import subprocess
import os

repo_dir = "/content/BIMASTER-TCC-projeto-gestao-despesas"


repo_url = (
    "https://github.com/KarineVersieux/"
    "BIMASTER-TCC-projeto-gestao-despesas.git"
)

print(repo_url)

result = subprocess.run(
    ["git", "clone", repo_url, repo_dir],
    capture_output=True,
    text=True
)

if result.returncode == 0:
    print("Projeto clonado com sucesso!")
else:
    print("Erro ao clonar:")
    print(result.stderr)

https://github.com/KarineVersieux/BIMASTER-TCC-projeto-gestao-despesas.git
Projeto clonado com sucesso!

In [2]:
# ------------------------------------------------------------
# 2. Definir pasta do projeto
# ------------------------------------------------------------
%cd /content/BIMASTER-TCC-projeto-gestao-despesas
pwd = !pwd
print("Pasta do projeto:", pwd[0])

/content/BIMASTER-TCC-projeto-gestao-despesas
Pasta do projeto: /content/BIMASTER-TCC-projeto-gestao-despesas

In [4]:
# ------------------------------------------------------------
# 3. Carregar o conteúdo .env
# ------------------------------------------------------------

!pip install python-dotenv -q

from dotenv import load_dotenv
import os

# Carrega as variáveis do .env
load_dotenv("/content/.env", override=True)


# Modelos
print("SQL_LLM_MODEL:", os.getenv("SQL_LLM_MODEL"))
print("EXTRACT_LLM_MODEL:", os.getenv("EXTRACT_LLM_MODEL"))

# Projeto
repo_dir = "/content/BIMASTER-TCC-projeto-gestao-despesas"

print("Projeto existe:", os.path.exists(repo_dir))

SQL_LLM_MODEL: gemini-3.5-flash-lite
EXTRACT_LLM_MODEL: gemini-3.5-flash
Projeto existe: True

In [5]:
# ------------------------------------------------------------
# 4. Instalar dependências
# ------------------------------------------------------------
import subprocess
import sys
from pathlib import Path

projeto_path = Path.cwd()
requirements = projeto_path /  "requirements.txt"

if not requirements.exists():
    raise FileNotFoundError(f"requirements.txt não encontrado em: {requirements}")

print("✓ Instalando dependências...")

subprocess.run(
    [
        sys.executable,
        "-m",
        "pip",
        "install",
        "-r",
        str(requirements)
    ],
    check=True
)

✓ Instalando dependências...

CompletedProcess(args=['/usr/bin/python3', '-m', 'pip', 'install', '-r', '/content/BIMASTER-TCC-projeto-gestao-despesas/requirements.txt'], returncode=0)

# EXECUÇÃO FUNÇÃO PRINCIPAL

In [ ]:
#CODIGO OBRA/CONTRATO VALIDO PARA TESTES: CASSIANO#01
from projeto_obras import main as obras

obras.main()

# 🏁EXEMPLOS DE CASOS DE TESTE E SAÍDAS

In [6]:
from projeto_obras import main as obras

obras.main()
# Caso de Teste 1: Não informar código e obra e encerrar

============================================================
       SISTEMA DE ANÁLISE DE RELATORIOS DE DESPESAS DE OBRAS
============================================================

 Digite o código da obra/contrato ou 0 - Sair:

 ❌ Nenhum código de obra foi informado.

 Digite o código da obra/contrato ou 0 - Sair:0

 🏁 Execução Encerrada

In [7]:
from projeto_obras import main as obras

obras.main()
#Caso de Teste 2: Digitação de código de obra/contrato invalido

============================================================
       SISTEMA DE ANÁLISE DE RELATORIOS DE DESPESAS DE OBRAS
============================================================

 Digite o código da obra/contrato ou 0 - Sair:789O


 Código Obra Informado:  789O

 ❌Código de Obra/Contrato não Cadastrado: '789O'

 Digite o código da obra/contrato ou 0 - Sair:675GT


 Código Obra Informado:  675GT

 ❌Código de Obra/Contrato não Cadastrado: '675GT'

 Digite o código da obra/contrato ou 0 - Sair:0

 🏁 Execução Encerrada

In [8]:
from projeto_obras import main as obras

obras.main()
# Caso de Teste 3: Digitação de código de obra/contrato VALIDO e GERAÇAO DE RELATORIO CONSOLIDADO

============================================================
       SISTEMA DE ANÁLISE DE RELATORIOS DE DESPESAS DE OBRAS
============================================================

 Digite o código da obra/contrato ou 0 - Sair:CASSIANO#01


 Código Obra Informado:  CASSIANO#01
⚠️ Serão processados dados somente do cliente: CASSIANO HAMACEK DE FREITAS

 Escolha uma opção:
1 - Processar relatório(s) de despesas
2 - Gerar relatório consolidado
3 - Consultar dados (Use linguagem natural)
0 - Sair

 Digite a opção desejada: 2

########################################################################

➡️ Geração de Relatório Consolidado ...

########################################################################

 Compilando documento estruturado em: /content/outputs/Gestão de Despesas/consolidado_20261006_124045.pdf

 ✅ Concluído! Relatório gerado com sucesso.

 Relatório: /content/outputs/Gestão de Despesas/consolidado_20261006_124045.pdf

 Escolha uma opção:
1 - Processar relatório(s) de despesas
2 - Gerar relatório consolidado
3 - Consultar dados (Use linguagem natural)
0 - Sair

 Digite a opção desejada: 0

 🏁 Execução Encerrada

In [9]:
from projeto_obras import main as obras

obras.main()
#Caso de Teste 4: Digitação de código de obra/contrato VALIDO  e selecionar arquivo já PROCESSADO

============================================================
       SISTEMA DE ANÁLISE DE RELATORIOS DE DESPESAS DE OBRAS
============================================================

 Digite o código da obra/contrato ou 0 - Sair:CASSIANO#01


 Código Obra Informado:  CASSIANO#01
⚠️ Serão processados dados somente do cliente: CASSIANO HAMACEK DE FREITAS

 Escolha uma opção:
1 - Processar relatório(s) de despesas
2 - Gerar relatório consolidado
3 - Consultar dados (Use linguagem natural)
0 - Sair

 Digite a opção desejada: 1

########################################################################

➡️ Processamento dos relatórios selecionados será executado ...

########################################################################

Saving N01 - 23-02 A 02-03.pdf to N01 - 23-02 A 02-03.pdf


 - N01 - 23-02 A 02-03.pdf

 ❌ Relatório de Prestação de Contas processado anteriomente (Número: '01' | Data: '2026-09-29T21:16:42.02007+00:00')

 ⚙️ Executando a Conciliação de Despesas e Comprovantes Disponíveis ...

 Escolha uma opção:
1 - Processar relatório(s) de despesas
2 - Gerar relatório consolidado
3 - Consultar dados (Use linguagem natural)
0 - Sair

 Digite a opção desejada: 0

 🏁 Execução Encerrada

In [10]:
from projeto_obras import main as obras

obras.main()
#Caso de Teste 5: Digitação de código de obra/contato VALIDO  e selecionar relatórios ainda NÃO PROCESSADOS

============================================================
       SISTEMA DE ANÁLISE DE RELATORIOS DE DESPESAS DE OBRAS
============================================================

 Digite o código da obra/contrato ou 0 - Sair:CASSIANO#01


 Código Obra Informado:  CASSIANO#01
⚠️ Serão processados dados somente do cliente: CASSIANO HAMACEK DE FREITAS

 Escolha uma opção:
1 - Processar relatório(s) de despesas
2 - Gerar relatório consolidado
3 - Consultar dados (Use linguagem natural)
0 - Sair

 Digite a opção desejada: 1

########################################################################

➡️ Processamento dos relatórios selecionados será executado ...

########################################################################

Saving N27 28-09 a 05-10.pdf to N27 28-09 a 05-10.pdf


 - N27 28-09 a 05-10.pdf

🟢 Processamento em andamento:  N27 28-09 a 05-10.pdf

-> gemini-3.5-flash para extração dos dados do relatorio PDF (processamento multimodal nativo) ...

✅ Sucesso! Relatório  27  e todas as suas dependências foram salvos.

 ⚙️ Executando a Conciliação de Despesas e Comprovantes Disponíveis ...

 Escolha uma opção:
1 - Processar relatório(s) de despesas
2 - Gerar relatório consolidado
3 - Consultar dados (Use linguagem natural)
0 - Sair

 Digite a opção desejada: 0

 🏁 Execução Encerrada

In [12]:
from projeto_obras import main as obras

obras.main()
#Caso de Teste 6: Digitação de código de obra/contato VALIDO e realizar CONSULTAS a base de dados, usando LINGUAGEM NATURAL

============================================================
       SISTEMA DE ANÁLISE DE RELATORIOS DE DESPESAS DE OBRAS
============================================================

 Digite o código da obra/contrato ou 0 - Sair:CASSIANO#01


 Código Obra Informado:  CASSIANO#01
⚠️ Serão processados dados somente do cliente: CASSIANO HAMACEK DE FREITAS

 Escolha uma opção:
1 - Processar relatório(s) de despesas
2 - Gerar relatório consolidado
3 - Consultar dados (Use linguagem natural)
0 - Sair

 Digite a opção desejada: 3
/n catalogo_texto:

########################################################################

➡️ Consulta a Dados ...

########################################################################

 Digite sua consulta aos dados em linguagem natural:
> INDIQUE O TOTAL DE DESPESAS DO ANO DE 2026

-> gemini-3.5-flash-lite para a geração da consulta...

================================================================================

📚 SQL GERADO:
================================================================================

  SELECT SUM(d.vlr_despesa) AS total_despesas FROM public."Despesa" d INNER JOIN public."Relatorio" r ON d.id_relatorio = r.id_relatorio WHERE r.id_contrato = 1 AND EXTRACT(YEAR FROM d.dta_despesa) = 2026;

================================================================================

💡 EXPLICAÇÃO:
================================================================================

  A consulta calcula o somatório do valor das despesas para o contrato com id_contrato igual a 1, filtrando apenas os lançamentos realizados no ano de 2026, utilizando a junção entre Despesa e Relatorio.

 ✅ Sucesso! Consulta realizada com sucesso.

 Quantidade de registros: 1

   total_despesas
0        72429.65

 Escolha uma opção:
1 - Processar relatório(s) de despesas
2 - Gerar relatório consolidado
3 - Consultar dados (Use linguagem natural)
0 - Sair

 Digite a opção desejada: 3
/n catalogo_texto:

########################################################################

➡️ Consulta a Dados ...

########################################################################

 Digite sua consulta aos dados em linguagem natural:
> resultado da eleição 2026

-> gemini-3.5-flash-lite para a geração da consulta...

================================================================================

💡 EXPLICAÇÃO:
================================================================================

  A pergunta fornecida sobre 'resultado da eleição 2026' não está relacionada ao escopo do sistema de prestação de contas de despesas com condomínios/obras e ao catálogo de dados disponível. Por favor, forneça uma pergunta relacionada às despesas, relatórios ou comprovantes.


 ❌  Nenhum SQL foi informado. False

 Escolha uma opção:
1 - Processar relatório(s) de despesas
2 - Gerar relatório consolidado
3 - Consultar dados (Use linguagem natural)
0 - Sair

 Digite a opção desejada: 3
/n catalogo_texto:

########################################################################

➡️ Consulta a Dados ...

########################################################################

 Digite sua consulta aos dados em linguagem natural:
> relatorios processados

-> gemini-3.5-flash-lite para a geração da consulta...

================================================================================

📚 SQL GERADO:
================================================================================

  SELECT id_relatorio, num_relatorio, nome_relatorio, dta_processamento, total_a_pagar FROM public."Relatorio" WHERE id_contrato = 1

================================================================================

💡 EXPLICAÇÃO:
================================================================================

  Consulta para listar os relatórios processados filtrando pelo id_contrato 1 conforme o parâmetro obrigatório.

 ✅ Sucesso! Consulta realizada com sucesso.

 Quantidade de registros: 20

,id_relatorio,num_relatorio,nome_relatorio,dta_processamento,total_a_pagar
0,174,01,N01 - 23-02 A 02-03.pdf,2026-09-29 21:16:42.020070+00:00,1558.19
1,175,14,N14 - 01-06 A 08-06.pdf,2026-09-29 21:26:42.940953+00:00,581.29
2,176,18,N18 - 29-06 A 06-07.pdf,2026-09-29 21:27:11.701349+00:00,1276.26
3,177,17,N17 - 22-06 A 29-06.pdf,2026-09-29 21:27:52.409664+00:00,281.24
4,178,16,N16 - 15-06 A 22-06.pdf,2026-09-29 21:28:31.821305+00:00,3246.65
5,179,15,N15 - 08-06 A 15-06.pdf,2026-09-29 21:29:32.017421+00:00,8030.01
6,180,20,N20 - 13-07 A 20-07.pdf,2026-10-01 20:29:56.373755+00:00,1391.58
7,181,02,N02 - 02-03 A 09-03.pdf,2026-10-02 02:47:52.110498+00:00,8713.93
8,182,12,N12 - 18-05 A 25-05.pdf,2026-10-02 13:34:52.571030+00:00,5619.72
9,183,13,N13 - 25-05 A 01-06.pdf,2026-10-02 13:35:06.043047+00:00,4863.02
10,184,03,N03 - 16-03 A 23-03.pdf,2026-10-02 13:50:59.919490+00:00,14858.09
11,185,06,N06 - 06-04 A 13-04.pdf,2026-10-03 10:24:30.499732+00:00,1267.69
12,186,04,N04 - 23-03 A 30-03.pdf,2026-10-03 11:48:18.285664+00:00,4711.99
13,187,05,N05 - 30-03 A 06-04.pdf,2026-10-03 11:48:35.259909+00:00,1568.22
14,188,07,N07 - 13-04 A 20-04.pdf,2026-10-03 11:57:40.642795+00:00,8874.83
15,189,08,N08 - 20-04 A 27-04.pdf,2026-10-03 11:57:57.280367+00:00,5524.00
16,190,09,N09 - 27-04 A 04-05.pdf,2026-10-03 12:56:33.422306+00:00,2473.82
17,191,10,N10 - 04-05 A 11-05.pdf,2026-10-03 12:56:53.052717+00:00,13319.95
18,192,26,N26 14-09 a 21-09.pdf,2026-10-04 12:53:42.467741+00:00,963.95
19,193,27,N27 28-09 a 05-10.pdf,2026-10-06 12:45:54.658659+00:00,162.36

 Escolha uma opção:
1 - Processar relatório(s) de despesas
2 - Gerar relatório consolidado
3 - Consultar dados (Use linguagem natural)
0 - Sair

 Digite a opção desejada: 3
/n catalogo_texto:

########################################################################

➡️ Consulta a Dados ...

########################################################################

 Digite sua consulta aos dados em linguagem natural:
> total de despesas por categoria

-> gemini-3.5-flash-lite para a geração da consulta...

================================================================================

📚 SQL GERADO:
================================================================================

  SELECT d.des_categoria, SUM(d.vlr_despesa) AS total_despesa FROM public."Despesa" d INNER JOIN public."Relatorio" r ON d.id_relatorio = r.id_relatorio WHERE r.id_contrato = 1 GROUP BY d.des_categoria

================================================================================

💡 EXPLICAÇÃO:
================================================================================

  A consulta calcula o total de despesas agrupadas por categoria, realizando a junção entre a tabela Despesa e Relatório para filtrar pelo id_contrato obrigatório igual a 1.

 ✅ Sucesso! Consulta realizada com sucesso.

 Quantidade de registros: 10

                     des_categoria  total_despesa
0             Logística/Transporte        1082.23
1              Material de Pintura        7857.07
2              Material de Limpeza         358.43
3                Material Elétrico       30268.98
4  Material de Bombeiro/Hidraulico        9971.10
5               Serviços Terceiros        4166.60
6                           Outros        2582.15
7             Material de Pedreiro       13512.38
8                Material de Gesso         180.00
9             Material de Proteção        2675.71

 Escolha uma opção:
1 - Processar relatório(s) de despesas
2 - Gerar relatório consolidado
3 - Consultar dados (Use linguagem natural)
0 - Sair

 Digite a opção desejada: 3
/n catalogo_texto:

########################################################################

➡️ Consulta a Dados ...

########################################################################

 Digite sua consulta aos dados em linguagem natural:
> despesas pendetes de compovação. indicar descrição, data, valor e relatorio

-> gemini-3.5-flash-lite para a geração da consulta...

================================================================================

📚 SQL GERADO:
================================================================================

  SELECT d.des_aplicacao, d.dta_despesa, d.vlr_despesa, r.num_relatorio, r.nome_relatorio FROM public."Despesa" d JOIN public."Relatorio" r ON d.id_relatorio = r.id_relatorio WHERE d.cod_status_comprovacao ILIKE 'PENDENTE' AND r.id_contrato = 1

================================================================================

💡 EXPLICAÇÃO:
================================================================================

  Consulta para listar as despesas pendentes de comprovação filtradas pelo contrato id 1, trazendo a descrição (des_aplicacao), data, valor e as informações do relatório associado.

 ✅ Sucesso! Consulta realizada com sucesso.

 Quantidade de registros: 18

,des_aplicacao,dta_despesa,vlr_despesa,num_relatorio,nome_relatorio
0,Material Elétrico,2026-03-20,11945.08,03,N03 - 16-03 A 23-03.pdf
1,Pintura do banheiro do vizinho,2026-04-22,300.00,07,N07 - 13-04 A 20-04.pdf
2,Material de Pedreiro,2026-04-23,1871.50,08,N08 - 20-04 A 27-04.pdf
3,Impermeabilizante comprado do cliente Alberto ...,2025-09-24,225.00,08,N08 - 20-04 A 27-04.pdf
4,serralheiro - 50% do reforço para porta quarto...,2026-04-27,1340.00,08,N08 - 20-04 A 27-04.pdf
5,Material Hidráulico,2026-04-09,107.30,06,N06 - 06-04 A 13-04.pdf
6,Impressão de projeto - hidraulico,2026-03-06,55.60,02,N02 - 02-03 A 09-03.pdf
7,Subir marcos de portas,2026-04-12,50.00,06,N06 - 06-04 A 13-04.pdf
8,Material Hidráulico,2026-04-13,240.00,06,N06 - 06-04 A 13-04.pdf
9,Tolentino Materiais de Construção,2026-06-02,99.00,14,N14 - 01-06 A 08-06.pdf
10,Retirada do material - Real Comércio -> obra,2026-06-25,5.65,17,N17 - 22-06 A 29-06.pdf
11,Material de Pedreiro,2026-04-30,963.50,09,N09 - 27-04 A 04-05.pdf
12,"Material de Pedreiro (Valor da NF R$ 1090,00, ...",2026-05-06,776.30,10,N10 - 04-05 A 11-05.pdf
13,"50%- reforço para porta - 2/2 - R$ 1340,00 + R...",2026-05-07,1527.60,10,N10 - 04-05 A 11-05.pdf
14,"Material de Pedreiro (Valor da NF R$ 1770,00, ...",2026-05-11,825.00,10,N10 - 04-05 A 11-05.pdf
15,Material Elétrico,2026-05-21,44.00,12,N12 - 18-05 A 25-05.pdf
16,Material Hidraulico (o valor da NF está R$ 344...,2026-04-02,104.67,05,N05 - 30-03 A 06-04.pdf
17,PAGAMENTO REF A RETIRADA E CARREGAMENO DA PORT...,2026-09-02,200.00,26,N26 14-09 a 21-09.pdf

 Escolha uma opção:
1 - Processar relatório(s) de despesas
2 - Gerar relatório consolidado
3 - Consultar dados (Use linguagem natural)
0 - Sair

 Digite a opção desejada: 0

 🏁 Execução Encerrada